promise


Fulfilled (Resolved):
    will call .then()
    
Rejected: as well as Error:
    call .catch()
